export const data = {
	name: 'IT sales club | Outsourcing, Outstaffing 🇺🇦',
	type: 'public_supergroup',
	id: 1275137343,
	messages: [
		{
			id: 1,
			date: '2021-06-11T16:36:33',
			from: 'Ilya Podavalkin',
			text: 'Middle+ Python Developer\nWe are looking for a Middle+ Python developer to join our project on an outstaffing basis. \nThis is an ongoing project with the global team, partly in the USA, the UK, and Ukraine). \nDuration: 6+ months allocation, fulltime\nProcess: Hr interview, Tech, Background check\nRequirements:\nProficient in Python Programming\nData engineering experience\nSome experience with Panda and/or Numpy (Critical)\nExperience with Airflow\nSoft skills and advanced English (Critical). \n6+ months, full-time.',
			structuredText: {
				typeOfOffer: 'lookfor',
				stack: 'Python',
				seniority: 'middle+',
				experience: '6',
				english: 'advanced',
				location: 'USA',
				rate: 'Not provided',
				contacts: 'Not provided',
			},
		},
		{
			id: 2,
			date: '2021-06-11T16:41:45',
			from: 'Yura Prokofiev',
			text: 'Strong Junior/Middle JavaScript developer (Angular2+)\nWe are looking for a Middle+ JavaScript developer to join',
			structuredText: {
				typeOfOffer: 'lookfor',
				stack: 'JavaScript developer (Angular2+)',
				seniority: 'Strong Junior/Middle',
				experience: 'at least 2 years of commercial experience',
				english: 'Intermediate or higher',
				location: 'Lviv, Ukraine (remote work or work in our Lviv office)',
				rate: 'Salary is from $1800 per month',
				contacts: 'Not provided',
			},
		},
		{
			id: 3,
			date: '2021-06-11T16:53:41',
			from: 'Oleh Pylyp',
			text: 'We are looking for a Senior Scala Developer\n\nRequired Skills\n● Primary usage of Mac/Linux for development is a must.\n● At least 3 years of full-time, hands on, continuous experience with Scala deliveringactual applications for businesses.\n● At least 2 years of experience with Akka, especially Akka Streams with heavy usageof Graph DSL and authoring custom GraphStages in real-world reactive-streamsystems.\n● At least 1 year of experience with Functional Programming using one or acombination of multiple effect management libraries: ZIO, Monix, Cats Effect, etc.\n● Experience with typeclass derivation using Shapeless or Magnolia for customencoders/decoders.\n● Experience with binary serialization libraries: Avro4s (Avro) and/or ScalaPB(Protobuf)\n● Experience with schema management and schema evolution. \n● Experience with Docker/containers in some production settings outside of just local/personal experimentation.\n● The desire to continuously learn and take on technical challenges outside of their comfort zone.\n\nCurrent project\nImmediate project is reimplementation of a legacy SMS/MMS platform to achieve 50-100x improvement in throughput, which is required to achieve global scale to handle most of the A2P messaging traffic in North America and beyond.',
			structuredText: {
				typeOfOffer: 'lookfor',
				stack: 'Scala',
				seniority: ' Senior',
				experience: 'At least 1 year',
				english: 'Not specified',
				location: 'Not specified',
				rate: 'Not specified',
				contacts: 'Not provided',
			},
		},
		{
			id: 45,
			date: '2021-06-14T07:18:52',
			from: 'Klempouz Tania',
			text: '\nHello! 🙂\nFor subcontracting we need:\nMiddle Strong\\Senior Front-End Developer for full-time.\nRequirements:\n- experience with D3.js\n- React.JS\nCandidates without D3.js are also considered!\nEnglish - Upper-Intermediate, there will be direct communication with the client.\nStart - asap, duration - initially 2 months, with a possible extension.\n\nMaybe someone else has a part-time Node.js Architect for a few hours a week?\n \nI will be very grateful! Send CVs and resumes of candidates by mail',
			structuredText: {
				typeOfOffer: 'lookfor',
				stack: 'Front-End',
				seniority: 'Middle Strong/Senior',
				experience: 'Not specified',
				english: 'Upper-Intermediate',
				location: 'Not specified',
				rate: 'Not specified',
				contacts: 'Not provided',
			},
		},
		{
			id: 54,
			date: '2021-06-14T12:54:52',
			from: 'Krystina Yasinska',
			text: 'Hello everybody! 🙂\nSubcontracting requires:\nMiddle Strong\\Senior Full Stack developer full-time.\nRequirements:\n- experience with .NET for Middle from 3 years, for Senior from 5 years\n- experience with Angular (8-11 versions) from 2 years old\nEnglish - Upper-Intermediate, direct communication with the client\nduration - initially 3 months, possible extension.\n\nThank you in advance! Send CVs and resumes of candidates to the post office',
			structuredText: {
				typeOfOffer: 'lookfor',
				stack: 'Full Stack Developer (.NET and Angular)',
				seniority: 'Middle Strong/Senior',
				experience:
					'.NET: Middle - at least 3 years, Senior - at least 5 years, Angular (8-11 versions): at least 2 years',
				english: 'Upper-Intermediate',
				location: 'Not specified',
				rate: 'Not specified',
				contacts: 'Not provided',
			},
		},
	],
};
